#trying
women

#vectors----
(v1=c('A','B','C'))
(v2=c(1,2,3))
(v3=c(True,False,True))
(v4=1:10)
v4
(v5=seq(1,10,2))
df=data.frame(rollno=c(1,2,3))
(v6[-c(5,3,5)])
v4[v4>150]
(v4=100:200)
v7=c('A','C')
(v8=1:3)
names(v8)=c('bhavya','riddhi','nihali')
v8['riddhi']
v8[2]
str(v8)
str(v1)
str(v2)
df=data.frame(rollno=c(1,2,3),name=c('riddhi','bhavya','nihali'),dept=c('dep1','dep2','dep3'),marks=floor(runif(3,50,100)))
df
df=fix(df)
df
ls()
#rm(list=ls())
(mylist=list(1,df,v4))
?matrix
(mymatrix=matrix(1:24,ncol=4,byrow=TRUE))
(mymat=matrix(1:16,nrow=3,byrow=FALSE))
(mymat=matrix(1:16,nrow=4))
(myarray=array(1:24,dim=c(4,3,2),dimnames = list(c('s1','s2','s3','s4'),c('sub1','sub2','sub3'),c('dep1','dep2'))))
myarray=fix(myarray)
df
df$rollno
df$name
df$dept
df$marks
table(df$rollno,df$name)
str(df)
df$name=factor(df$name)
str(df)

df$marks=factor(df$dept.ordered=T,labels=c('c','b','a'))
